name: Terraform Lint & Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Run tflint
        uses: terraform-linters/setup-tflint@v1
      - run: tflint

      - name: Terraform Plan
        run: terraform plan
